# Generated by Django 4.0.3 on 2022-03-17 12:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneOtp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=12, unique=True, validators=[django.core.validators.RegexValidator(message='Invalid phone number.', regex='^989\\d{2}\\s*?\\d{3}\\s*?\\d{4}$')], verbose_name='phone')),
                ('otp', models.CharField(max_length=6)),
                ('count', models.PositiveSmallIntegerField(default=0, help_text='Number of otp sent')),
                ('verify', models.BooleanField(default=False, verbose_name='is verify')),
            ],
        ),
    ]
