# Generated by Django 4.0.3 on 2022-03-31 16:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import extensions.upload_file_path


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_phoneotp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('status', models.BooleanField(default=False, verbose_name='Status')),
                ('parent', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='core.category', verbose_name='SubCategory')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='Slug')),
                ('body', models.TextField(verbose_name='Content')),
                ('image', models.ImageField(upload_to=extensions.upload_file_path.upload_file_path, verbose_name='Image')),
                ('summery', models.TextField(max_length=400, verbose_name='Summery')),
                ('publish', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Publish Time')),
                ('create', models.DateTimeField(auto_now_add=True, verbose_name='Create Time')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Update Time')),
                ('special', models.BooleanField(default=False, verbose_name='Is special blog?')),
                ('status', models.CharField(choices=[('p', 'publish'), ('d', 'draft')], max_length=1, verbose_name='Status')),
                ('visits', models.PositiveIntegerField(default=0, verbose_name='Visits')),
                ('author', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='blogs', to=settings.AUTH_USER_MODEL, verbose_name='Author')),
                ('category', models.ManyToManyField(blank=True, default=None, related_name='blogs', to='core.category', verbose_name='Categories')),
                ('likes', models.ManyToManyField(blank=True, related_name='blogs_like', to=settings.AUTH_USER_MODEL, verbose_name='Likes')),
            ],
            options={
                'verbose_name': 'Blog',
                'verbose_name_plural': 'Blogs',
                'ordering': ('-publish', '-updated'),
            },
        ),
    ]
